### PR TITLE
Simple Indentation

### PR DESCRIPTION
**Pull request by kopecs**
As a temporary measure before #33 (specifically, whole AST based document formatting) is finalized this provides for fairly basic whole document (re)indentation within blocks enclosed by `{ }`, i.e., block statements, and `( )`, with a typical use case of multi-line function calls.

### CODE REVIEW

**Comment by ishantheperson** [comment]
What happens if I do this

```
int foo(int x, int y) { 
  // if (bar(x) > y) {
  if (baz(y) >= y) {
    // ...
  }
}
```

**Comment by kopecs** [comment]
It works as intended and doesn't indent in comments.

**Comment by ishantheperson** [comment]
How heavily have you tested this? Especially on adverse inputs where braces appear in comments or strings etc

**Comment by kopecs** [comment]
This is the test file I've been using
```
/* { */
#use <string>

// Allows for usage of ){({
#use <conio>

bool foo() {
    // if (condt { then
    if (true) { // remember to )((
        return true;
    } else {
        return false;
    }
}

int main()
//@ensures foo();
{
    bool condition = false;
    // This function does (
    // the following operation (
    // { on data
    // }
    /* test { */ foo(); /* indentation */
    if (
        condition
    ) {
        //then code;
    }
    else {
        // alternative body;
        for (int j = 3; j < 67; j++)
        //@loop_invariant j < 69;
        {
            /* this ))((((((( */ j++; /* {{} */ // comment
            // look at this helpful )))))))))))))))))) documentation.
        }
    }
    multi_line_function_call(
        1,
        true,
        foo(),
        alloc(char)
    );
    return 0;
}
```
Shown as indented on latest commit (although nothing changed from earlier besides some consolidation of different tests). If you have some sort of edge case that isn't tested in this file let me know.

**Comment by ishantheperson** [comment]
How do you deal with things like this

```
int i = 
  foo(A[asd asoidj sefsdf] + bar()) + more expressions text;
```

**Comment by kopecs** [comment]
As-is the second part of the assignment is placed at the same indentation level; I can add an indent level between seeing an assignment operator and a semicolon though. Is there any other type of statement you would split across multiple lines like that?

**Comment by ishantheperson** [comment]
I mean any continuation of a statement will need to be indented. That's why I'm worried about this. These are just the issues I'm seeing by looking at the source code. The only actual test case I ran was the one with braces inside a string literal

**Pull request closed without merging**
