### PR TITLE
Cached dependencies

### PR DESCRIPTION
**Pull request by CalLavicka**
Now with more copying of typeIds. Basically the issue was we would update the types in the cache with whatever was defined, causing the next parse to conflict with the same id.

### CODE REVIEW

**Comment by ishantheperson** [comment]
It seems like this doesn't work with `#use "foo.c0"` 
Consider this scenario: you have two files `foo.c0` and `bar.c0.`

project.txt contains
```
foo.c0
bar.c0
```
but `foo.c0` uses `#use "bar.c0"`. 

In this case, after loading `foo.c0`, the genv will contain both `foo.c0` and `bar.c0` as `filesLoaded`. But then when trying to modify bar.c0, it will never actually get parsed since the cached genv from foo.c0 will already have bar.c0 as modified.

This occurs in Clac

**Comment by CalLavicka** [comment]
Ok, I think I see what the issue is and am working on a fix now.

**Comment by ishantheperson** [comment]
Part of the issue was that the document on disk might be out of date if it's being currently edited, so I pushed a fix for that to master (that issue existed before this)

**Comment by CalLavicka** [comment]
Just pushed a fix. #used files should now correctly invalidate the file which uses them when modified.

**Pull request merged**
