### PR TITLE
Made changes based on comments from PR #5

### PR DESCRIPTION
**Pull request by angelayi**
- Made internal class variables private
- made handleContextChanges a class function
- exported the WordListClass
- Used lex.ts to get the keywords

### CODE REVIEW

**Comment by ishantheperson** [comment]
Did you mean to close this?

**Comment by angelayi** [comment]
@ishantheperson sorry I meant to PR into my own repo. But I have made some changes according to the comments in the last PR. I'm not 100% sure how GitHub works, but if you have time do you mind taking a look at it? thanks!

**Comment by ishantheperson** [comment]
Lol yeah I will as soon as I finish my final which started 3 minutes ago

**Comment by CalLavicka** [comment]
@angelayi you can re-request a review from a reviewer by hitting the refresh button on the right-hand side of the PR page

**Comment by angelayi** [comment]
oo ok I got it thank you!

**Pull request closed without merging**
